//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BSI.Zimmer.Dominio.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

    public partial class Usuario : EntityBase, IValidatableObject
    {

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var validationResults = new List<ValidationResult>();

            if (string.IsNullOrWhiteSpace(this.Login))
                validationResults.Add(new ValidationResult(Messages.ValidationUsuarioLoginNaoPodeSerNulo));

            if (string.IsNullOrWhiteSpace(this.Nome))
                validationResults.Add(new ValidationResult(Messages.ValidationUsuarioNomeNaoPodeSerNulo));

            if (string.IsNullOrWhiteSpace(this.Senha))
                validationResults.Add(new ValidationResult(Messages.ValidationUsuarioSenhaNaoPodeSerNulo));

            if (!this.PerfilAcesso.HasValue)
                validationResults.Add(new ValidationResult(Messages.ValidationUsuarioPerfilAcessoNaoPodeSerNulo));


            return validationResults;
            
        }
    }
}

