//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSI.Zimmer.Dominio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSI.Zimmer.Dominio.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nao pode adicionar entidade nula.
        /// </summary>
        public static string info_NaoPodeAdicionarEntidadeNula {
            get {
                return ResourceManager.GetString("info_NaoPodeAdicionarEntidadeNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nao pode remover entidade nula.
        /// </summary>
        public static string info_NaoPodeRemoverEntidadeNula {
            get {
                return ResourceManager.GetString("info_NaoPodeRemoverEntidadeNula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Campo Nome é obrigatório.
        /// </summary>
        public static string Validation_CampoNomeObrigatorio {
            get {
                return ResourceManager.GetString("Validation_CampoNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo login da entidade não pode ser nulo.
        /// </summary>
        public static string ValidationUsuarioLoginNaoPodeSerNulo {
            get {
                return ResourceManager.GetString("ValidationUsuarioLoginNaoPodeSerNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome da entidade não pode ser nulo.
        /// </summary>
        public static string ValidationUsuarioNomeNaoPodeSerNulo {
            get {
                return ResourceManager.GetString("ValidationUsuarioNomeNaoPodeSerNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Perfil Acesso da entidade não pode ser nulo.
        /// </summary>
        public static string ValidationUsuarioPerfilAcessoNaoPodeSerNulo {
            get {
                return ResourceManager.GetString("ValidationUsuarioPerfilAcessoNaoPodeSerNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Senha da entidade não pode ser nulo.
        /// </summary>
        public static string ValidationUsuarioSenhaNaoPodeSerNulo {
            get {
                return ResourceManager.GetString("ValidationUsuarioSenhaNaoPodeSerNulo", resourceCulture);
            }
        }
    }
}
