//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BSI.Zimmer.Dominio.Entity
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Avaliacao : EntityBase
	{
		public virtual DateTime DataAvaliacao
		{
			get;
			set;
		}

		public virtual Usuario Usuario
		{
			get;
			set;
		}

		public virtual IEnumerable<QuestaoAvaliada> Questoes
		{
			get;
			set;
		}

		public virtual CheckList CheckList
		{
			get;
			set;
		}

		public virtual Projeto Projeto
		{
			get;
			set;
		}

		public virtual Avaliacao AvaliacaoPai
		{
			get;
			set;
		}

	}
}

