//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BSI.Zimmer.Dominio.Entity
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Cliente : EntityBase
	{
		public virtual string Nome
		{
			get;
			set;
		}

		public virtual Int32 PackageId
		{
			get;
			set;
		}

		public virtual ICollection<Projeto> Projetos
		{
			get;
			set;
		}

	}
}

