//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BSI.Zimmer.Dominio.Entity
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class QuestaoAvaliada : EntityBase
	{
		public virtual Conformidade Conformidade
		{
			get;
			set;
		}

		public virtual Questao QuestaoPertencente
		{
			get;
			set;
		}

		public virtual Avaliacao Avaliacao
		{
			get;
			set;
		}

	}
}

