//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BSI.Zimmer.Dominio.Entity
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Questao : EntityBase
	{
		public virtual string Nome
		{
			get;
			set;
		}

		public virtual string Descricao
		{
			get;
			set;
		}

		public virtual string Evidencia
		{
			get;
			set;
		}

		public virtual string DeveSeguir
		{
			get;
			set;
		}

		public virtual string DeveEvitar
		{
			get;
			set;
		}

		public virtual CategoriaQuestao CategoriaQuestao
		{
			get;
			set;
		}

		public virtual CheckList CheckList
		{
			get;
			set;
		}

        public virtual ICollection<QuestaoAvaliada> Avaliacao
		{
			get;
			set;
		}

	}
}

