//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BSI.Zimmer.Dominio.Entity
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Usuario : EntityBase
	{
		public virtual string Nome
		{
			get;
			set;
		}

		public virtual string Login
		{
			get;
			set;
		}

		public virtual string Senha
		{
			get;
			set;
		}

		public virtual PerfilAcesso? PerfilAcesso
		{
			get;
			set;
		}

	}
}

